### ISSUE TITLE
YAML comments are removed from original file upon export (First occurrence V1.5.4 to V1.6.1)

### ISSUE THREAD

**Issue by PxaMMaxP** [mokeyish/obsidian-enhancing-export#97]
Hello,

The error first occurred after the update from version 1.5.4 to 1.6.1. When I export a .md file and the wait window disappears, the original file no longer contains any comments in the YAML section.

I was able to reproduce the error when changing the version (see above). All other plugins were disabled (Test Vault).

My JavaScript skills are not good. Nonetheless, I've looked at what changes were made in the version jump. Unfortunately, I can't find the error.

Example before export:
```
---
type: Task
# Short description of the goals
description: Example Task
# Task status (Active, Waiting, Later, Someday, Done)
status: Active
# Priority points (eg. 0 = low, 3 = high)
priority: 3
# Energy requirements points (eg. 0 = low energy, 3 = high energy necessary)
energy: 1
# Timing in h (eg. 0,5h, 1h, 5h)
time: 0.5h
# Tags without hashtag (eg. \n - "23ABCD" instead of "#23ABCD")
tags:
 - 23VLvmSTVAk
# Due date (Format: yyyy-MM-DD)
due: 2023-07-02
---
Text for the letter!
```

Example after export:
```
---
type: Task
description: Example Task
status: Active
priority: 3
energy: 1
time: 0.5h
tags:
 - 23VLvmSTVAk
due: 2023-07-02
---
Text for the letter!
```

**Comment by mokeyish** [comment]
The latest version is 1.8.3, can you upgrade it first or reinstall it?

**Comment by mokeyish** [comment]
This plugin is based on pandoc, maybe you should check it if an issue with pandoc itself.

**Comment by PxaMMaxP** [comment]
I have tried the versions and the error occurred only with version 1.6.1.

It is not due to Pandoc.

I'll test it again by reinstalling the plugin completely with the latest version and then write another ma.

**Comment by PxaMMaxP** [comment]
I have now tested it with a fresh Vault.

The problem persists. Comments in the YAML header are removed. The Pandoc version on my computer is the same in the main Vault with version 1.5.4 of your plugin.

With 1.5.4 the error does not occur, with any higher version it does.

Example MD file before export:
```
---
# ########################################
# ############ Letter ####################
# - Settings - (Comment out for disable options)
template: Letter
version: 2.0
stripComments: false
# e.g. false, a-2b, a-3b etc.
pdfa: a-2b 
draft: false
intern: false
noSig: true
# ########################################
# - Base informations from writer -
author: Max Mustermann
phone: 
return-address:
 - My Street 2
 - 99999 City
closing: Mit freundlichen Grüßen
opening: Sehr geehrte Damen und Herren,
# ########################################
# - Document informations -
place: 
date: 25.08.2023
subject: "Example Subject"
keywords: 
# ########################################
# - Adress field options -
postagebasefolder: ../Ressourcen/Frankierungen/
# - Insert file path in format (DIN A4 Normalpapier (Einlegeblatt)) with blank address.
#          e.g. FileInPostageFolder.pdf
postage: 
# - Specialmail text visible in address window.
postmark: 
# - Delivery notice outside the address window.
deliverynote: 
# ########################################
# - Project informations and references -
yourmailfrom: 
yourref: 
# e.g. Project hashtag
myref: "23Be"
otherref: "10.08.23 13:45 Uhr"
otherrefname: "Telefonat vom"
resubmissiondate: 
# ########################################
# - Recipient informations -
recipient: My Bank AG
address: 
 - Example Street 22
 - 00000 City
 - \phantom{PLACEHOLDE}
 - \phantom{PLACEHOLDE}
# ########################################
# - Attachment settings  -
attachmentbasefolder: ../
embedfile: false
addattachmentprefacepage: false
addattachments: true
addattachmentsraw: false
# ########################################
# - Attachments  -
attachments: 
- number: A1
  title: "2023.07.03 - Examplefile"
---
Example Mail Text..
```

Example after export:
```
---
template: Letter
version: 2
stripComments: false
pdfa: a-2b
draft: false
intern: false
noSig: true
author: Max Mustermann
phone: null
return-address:
  - My Street 2
  - 99999 City
closing: Mit freundlichen Grüßen
opening: Sehr geehrte Damen und Herren,
place: null
date: 25.08.2023
subject: Example Subject
keywords: null
postagebasefolder: ../Ressourcen/Frankierungen/
postage: null
postmark: null
deliverynote: null
yourmailfrom: null
yourref: null
myref: 23Be
otherref: 10.08.23 13:45 Uhr
otherrefname: Telefonat vom
resubmissiondate: null
recipient: My Bank AG
address:
  - Example Street 22
  - 00000 City
  - \phantom{PLACEHOLDE}
  - \phantom{PLACEHOLDE}
attachmentbasefolder: ../
embedfile: false
addattachmentprefacepage: false
addattachments: true
addattachmentsraw: false
attachments:
  - number: A1
    title: 2023.07.03 - Examplefile
---
Example Mail Text..
```
